import { NextIntlClientProvider } from "next-intl";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "../globals.css";

// Fuentes personalizadas
const geistSans = localFont({
  src: "../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  // Cargar mensajes de traducción
  const messages = await import(`../../texts/${params.locale}.json`);

  return (
    <html lang={params.locale || "en"}>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <NextIntlClientProvider locale={params.locale} messages={messages.default}>
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
