import { NextIntlClientProvider } from 'next-intl';  // Importa el proveedor de next-intl
import type { Metadata } from "next";
import localFont from "next/font/local";
import "../globals.css";

// Carga las fuentes personalizadas
const geistSans = localFont({
  src: "../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  // Cargar los mensajes según el locale
  const messages = await import(`../../texts/${params.locale}.json`);

  return (
    <NextIntlClientProvider locale={params.locale} messages={messages.default}>
      <html lang={params.locale || "en"}>
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          {children}
        </body>
      </html>
    </NextIntlClientProvider>
  );
}
